<div class="innerTextPadding">
    <a href="index.shtml">Home </a> <br />
    <br />
    <div class="subHeading">Tools</div>
    <a href="index_lab1.shtml">Final Grade Determiner</a> <br />
    <a href="index_lab2.shtml">Office Hours Setup Form</a> <br />
    <a href="index_lab3.shtml">Online Contacts Directory</a> <br />
    <a href="index_lab4.shtml">Mini Blog</a> <br />
</div>

<div class="innerTextPadding">
    <div class="subHeading">Others</div>
    <a href="index_practicum1.shtml">Metabolic Equivalents Energy Expender</a> <br />
</div>
