	<div>
		<h1>Huh?</h1>
		<h2>Latest news on Twitter reported on msn.com</h2> 
		<p> Good news for anyone that wants to pay Elon Musk $8 for a Twitter checkmark! The billionaire plans to re-launch his verification system next week, according to The Hollywood Reporter. The paid checkmark will remain blue, but checkmarks identifying governments will be changed to gray, and company checkmarks will turn gold.</p>
		<p><i>Citation: Moyer, P. (2022, november). Elon Musk Is Making Another Huge Change To Twitter. Retrieved from msn.com: https://www.msn.com/en-us/news/technology/elon-musk-is-making-another-huge-change-to-twitter/ar-AA14BVvp?ocid=entnewsntp&cvid=364cb808c6ee4ad9abbbc7ceb22e6e1d</i></p>
	</div>
